SchoolProject.WebApplication/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolProject.WebApplication.Models;
using SchoolProject.WebApplication.ServiceManager.Interface;
using SchoolProject.WebApplication.ViewModels;

namespace SchoolProject.WebApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    [HandleError]
    public class AdministrationController : _BaseController
    {
        private readonly IAdmininstrationManager _iAdminstrationManager;
        private ApplicationDatabaseContext dbContext;
        public AdministrationController(IAdmininstrationManager iAdmininstrationManager) {
            _iAdminstrationManager = iAdmininstrationManager;
            dbContext = new ApplicationDatabaseContext();
        }

        public ActionResult Status() {
            var status = _iAdminstrationManager.GetActiveStatuses();
            return View(status);
        }

        public ActionResult DocumentType() {
            var result = _iAdminstrationManager.GetActiveDocumentType();
            return View(result);
        }

        public ActionResult Terms() {
            var terms = _iAdminstrationManager.GetActiveTerms();
            return View(terms);
        }

        public ActionResult JobGrade() {
            var jobGrade = _iAdminstrationManager.GetActiveJobGrades();
            return View(jobGrade);
        }

        public ActionResult PerformanceYear() {
            var performanceYears = _iAdminstrationManager.GetPerformanceYears().Where(x => x.DateDeleted == null && x.StatusId != 4).ToList();
            return View(performanceYears);
        }

        public ActionResult PerformanceYearReviews() {
            var reviewPeriods = _iAdminstrationManager.GetReviewPeriods().Where(x => x.DateDeleted == null && x.StatusId != 4).ToList();
            return View(reviewPeriods);
        }

        public ActionResult PerformanceReviewPeriodLinking() {
            var reviewLinks = _iAdminstrationManager.GetLinkedPerformanceYearReviews();
            return View(reviewLinks);
        }

        public ActionResult OrganisationStructure() {
            var orgStructure = _iAdminstrationManager.GetActiveStructureOrganisation();
            return View(orgStructure);
        }

        public ActionResult Portfolios() {
            var result = _iAdminstrationManager.GetActiveStructurePortfolio();
            return View(result);
        }

        public ActionResult Department() {
            var results = _iAdminstrationManager.GetActiveStructureDepartment();
            return View(results);
        }

        public ActionResult Team() {
            var results = _iAdminstrationManager.GetActiveStructureTeam();
            return View(results);
        }

        public ActionResult ReviewReportingStructure() {
            var results = _iAdminstrationManager.GetPMReviewReportingStructure();
            return View(results);
        }

        public ActionResult Employees() {
            var results = _iAdminstrationManager.GetEmployee();
            return View(results);
        }

        [HttpGet]
        public ActionResult CreateEmployee() {
            if (TempData["viewModelEmployee"] != null) {
                return View((RegisterEmployee)TempData["viewModelEmployee"]);
            }
            else {
                var employee = new RegisterEmployee();
                employee.Team = GetJobTeams();
                employee.JobGrade = GetJobGrades();
                employee.FormMode = FormModeOption.CREATE;
                return View(employee);
            }
        }

        [HttpGet]
        public ActionResult UpdateEmployee(int? employeeRecordId) {
            if (employeeRecordId == null)
                return RedirectToAction("CreateEmployee");
            var dbEmployee = _iAdminstrationManager.FindEmployee((int)employeeRecordId);
            var viewModelEmployee = new RegisterEmployee() {
                EmployeeRecordId = dbEmployee.EmployeeRecordId,
                EmployeeCode = dbEmployee.EmployeeCode,
                NetworkUsername = dbEmployee.NetworkUsername,
                EmployeeName = dbEmployee.Name,
                EmployeeSurname = dbEmployee.Surname,
                JobGradeId = dbEmployee.JobGradeId,
                TeamId = dbEmployee.TeamId,
                JobGrade = GetJobGrades(),
                Team = GetJobTeams(),
                ProcessingStatusMessage = string.Empty,
                FormMode = FormModeOption.EDIT
            };
            TempData["viewModelEmployee"] = viewModelEmployee;
            return RedirectToAction("CreateEmployee");
        }

        [HttpGet]
        public ActionResult RemoveEmployee(int? employeeRecordId) {
            if (employeeRecordId == null)
                return RedirectToAction("CreateEmployee");

            var dbEmployee = _iAdminstrationManager.FindEmployee((int)employeeRecordId);
            var viewModelEmployee = new RegisterEmployee() {
                EmployeeRecordId = dbEmployee.EmployeeRecordId,
                EmployeeCode = dbEmployee.EmployeeCode,
                NetworkUsername = dbEmployee.NetworkUsername,
                EmployeeName = dbEmployee.Name,
                EmployeeSurname = dbEmployee.Surname,
                JobGradeId = dbEmployee.JobGradeId,
                TeamId = dbEmployee.TeamId,
                JobGrade = GetJobGrades(),
                Team = GetJobTeams(),
                ProcessingStatusMessage = string.Empty,
                FormMode = FormModeOption.DELETE
            };
            TempData["viewModelEmployee"] = viewModelEmployee;
            return RedirectToAction("CreateEmployee");
        }

        [HttpPost]
        public ActionResult CreateEmployee(RegisterEmployee registerEmployee) {

            if (ModelState.IsValid) {
                switch (registerEmployee.FormMode) {
                    case FormModeOption.CREATE: {
                            if (!EmployeeExist(registerEmployee.EmployeeCode)) {
                                var employee = TransformEmployee(registerEmployee);
                                dbContext.StructureEmployee.Add(employee);
                                dbContext.SaveChanges();

                                var createNew = new RegisterEmployee();
                                createNew.Team = GetJobTeams();
                                createNew.JobGrade = GetJobGrades();
                                createNew.FormMode = FormModeOption.CREATE;
                                createNew.ProcessingStatus = true;
                                createNew.ProcessingStatusMessage = string.Format("Successfully added employee {0} - {1} {2}",
                                                             registerEmployee.EmployeeCode, registerEmployee.EmployeeName,
                                                             registerEmployee.EmployeeSurname);
                                TempData["viewModelEmployee"] = createNew;
                                return RedirectToAction("CreateEmployee");
                            }
                            else {
                                ModelState.AddModelError(string.Empty, "Employee aready exist...");
                                break;
                            }
                        }
                    case FormModeOption.EDIT: {
                            var employee = _iAdminstrationManager.FindEmployee(registerEmployee.EmployeeRecordId);
                            employee.JobGradeId = registerEmployee.JobGradeId;
                            employee.TeamId = registerEmployee.TeamId;
                            employee.Name = registerEmployee.EmployeeName;
                            employee.Surname = registerEmployee.EmployeeSurname;
                            employee.NetworkUsername = registerEmployee.NetworkUsername;
                            employee.DateModified = DateTime.Now;
                            employee.ModifiedBy = "System";
                            dbContext.SaveChanges();
                            //DbEntityEntry entry = dbContext.Entry(employee);
                            //if (entry.State == EntityState.Detached) {
                            //    entry.State = EntityState.Modified;
                            //    dbContext.SaveChanges();
                            //}
                            
                            var createNew = new RegisterEmployee();
                            createNew.Team = GetJobTeams();
                            createNew.JobGrade = GetJobGrades();
                            createNew.FormMode = FormModeOption.CREATE;
                            createNew.ProcessingStatus = true;
                            createNew.ProcessingStatusMessage = string.Format("Successfully updated employee: {0} - {1} {2}",
                                                             registerEmployee.EmployeeCode, registerEmployee.EmployeeName,
                                                             registerEmployee.EmployeeSurname);
                            TempData["viewModelEmployee"] = createNew;
                            return RedirectToAction("CreateEmployee");
                        }
                    case FormModeOption.DELETE: {
                            var employee = _iAdminstrationManager.FindEmployee(registerEmployee.EmployeeRecordId);
                            employee.DeletedBy = "System";
                            employee.DateDeleted = DateTime.Now;
                            employee.StatusId = 2; //Deleted Status Id
                            dbContext.SaveChanges();
                            //DbEntityEntry entry = dbContext.Entry(employee);
                            //if (entry.State == EntityState.Detached) {
                            //    entry.State = EntityState.Modified;

SchoolProject.WebApplication/Views/Administration/LinkEmployeeToManager.cshtml
@model SchoolProject.WebApplication.ViewModels.LinkEmployeeManager
@using SchoolProject.WebApplication.ViewModels;

@{
    ViewBag.Title = "LinkEmployeeToManager";
}

@switch (Model.FormMode) {
    case FormModeOption.CREATE: {
            <h2>Link Employee To Manager</h2>
            break;
        }
    case FormModeOption.EDIT: {
            <h2>Update Employee Manager</h2>
            break;
        }
    case FormModeOption.DELETE: {
            <h2>Remove Employee Manager Link</h2>
            break;
        }
}

<hr />

@using (Html.BeginForm("ManageEmployeeManager", "Administration", FormMethod.Post, new { @id = "ManageEmployeeManagerLinkForm" })) {
    @Html.HiddenFor(model => model.FormMode)

    var formModes = Enum.GetValues(typeof(FormModeOption)).Cast<FormModeOption>().Where(i => i == FormModeOption.DELETE ||
                                                                                       i == FormModeOption.EDIT).ToList();
    if (formModes.Contains(Model.FormMode)) {
        @Html.HiddenFor(model => model.EmployeeReportingRecordId)
    }
    for (int i = 0; i < Model.Managers.Count; i++) {
        @Html.HiddenFor(model => Model.Managers[i].ValueText)
        @Html.HiddenFor(model => Model.Managers[i].DisplayText)
    }
    for (int i = 0; i < Model.Employees.Count; i++) {
        @Html.HiddenFor(model => Model.Employees[i].ValueText)
        @Html.HiddenFor(model => Model.Employees[i].DisplayText)
    }
    for (int i = 0; i < Model.DocumentTypes.Count; i++) {
        @Html.HiddenFor(model => Model.DocumentTypes[i].ValueText)
        @Html.HiddenFor(model => Model.DocumentTypes[i].DisplayText)
    }

    @*Display Error messages*@
if (!ViewData.ModelState.IsValid) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.ValidationSummary(true)
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (Model.ProcessingStatus)) {
    <div class="row">
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (!Model.ProcessingStatus)) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}

if (Model.FormMode == FormModeOption.DELETE) {
    @Html.HiddenFor(x => x.DocumentTypeId)
    @Html.HiddenFor(x => x.EmployeeRecordId)
    @Html.HiddenFor(x => x.ManagerRecordId)

        <div class="row">
            <div class="alert alert-danger alert-dismissable">
                <p>
                    @{ 
                        var employeeName = Model.Employees.FirstOrDefault(x => x.ValueText == Model.EmployeeRecordId.ToString()).DisplayText;
                        var managerName = Model.Managers.FirstOrDefault(x => x.ValueText == Model.ManagerRecordId.ToString()).DisplayText;
                    }
                    Are you sure you want to remove employee (@employeeName) - Manager(@managerName) Link?
                </p>
            </div>
        </div>
    }

    <div class="row">
        <div class="col-md-7">

            @if (Model.FormMode != FormModeOption.DELETE) {
                <div class="row">
                    @Html.Label("Employee", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("EmployeeRecordId", new SelectList(Model.Employees, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Employee"), new { @class = "form-control", @required = true })
                </div>
                <div class="row">
                    @Html.Label("Manager", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("ManagerRecordId", new SelectList(Model.Managers, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Manager"), new { @class = "form-control", @required = true })
                </div>

                <div class="row">
                    @Html.Label("Document Type", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("DocumentTypeId", new SelectList(Model.DocumentTypes, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Document Type"), new { @class = "form-control", @required = true })
                </div>
            }
            else {
                <div class="row">
                    @Html.Label("Employee", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("EmployeeRecordId", new SelectList(Model.Employees, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Employee"), new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div class="row">
                    @Html.Label("Manager", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("ManagerRecordId", new SelectList(Model.Managers, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Manager"), new { @class = "form-control", @disabled = "disabled" })
                </div>

                <div class="row">
                    @Html.Label("Document Type", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("DocumentTypeId", new SelectList(Model.DocumentTypes, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Document Type"), new { @class = "form-control", @disabled = "disabled" })
                </div>
            }
            <br />
            <div class="row">
                <a href="@Url.Action("ReviewReportingStructure", "Administration")" class="btn btn-md btn-primary" role="button">
                    <span class="glyphicon glyphicon-chevron-left glyphicon-chevron-left">
                    </span>&nbsp;Back To Link Employee To Manager Listing
                </a>
                    @switch (Model.FormMode) {
                        case FormModeOption.CREATE: {
                                <button id="SubmitCreateEmployee" type="submit" class="btn btn-md btn-primary">
                                    <span class="glyphicon glyphicon-plus">
                                    </span>&nbsp;Create Employee Manager
                                </button>
                                break;
                            }
                        case FormModeOption.EDIT: {
                                <button id="SubmitCreateEmployee" type="submit" class="btn btn-md btn-primary">
                                    <span class="glyphicon glyphicon-pencil">
                                    </span>&nbsp;Update Employee Manager Details
                                </button>
                                break;
                            }
                        case FormModeOption.DELETE: {
                                <button id="SubmitCreateEmployee" type="submit" class="btn btn-md btn-danger">
                                    <span class="glyphicon glyphicon-remove">
                                    </span>&nbsp;Remove Employee Manager Record
                                </button>
                                break;
                            }
                        default: {
                                break;
                            }
                    }
            </div>
            <br />
        </div>
    </div>
}

SchoolProject.WebApplication/Views/Administration/ManagePerformanceYear.cshtml
@model SchoolProject.WebApplication.ViewModels.RegisterPerformanceYear
@using SchoolProject.WebApplication.ViewModels;

@{
    ViewBag.Title = "ManageStrategicGoal";
}

@switch (Model.FormMode) {
    case FormModeOption.CREATE: {
            <h2>Create Performance Year</h2>
            break;
        }
    case FormModeOption.EDIT: {
            <h2>Update Performance Year</h2>
            break;
        }
    case FormModeOption.DELETE: {
            <h2>Remove Performance Year</h2>
            break;
        }
}

<hr />

@using (Html.BeginForm("ManagePerformanceYear", "Administration", FormMethod.Post, new { @id = "ManagePerformanceYearForm" })) {
    @Html.HiddenFor(model => model.FormMode)

    var formModes = Enum.GetValues(typeof(FormModeOption)).Cast<FormModeOption>().Where(i => i == FormModeOption.DELETE ||
                                                                                       i == FormModeOption.EDIT).ToList();
    if (formModes.Contains(Model.FormMode)) {
        @Html.HiddenFor(model => model.PerformanceYearId)
    }

    @*Display Error messages*@
if (!ViewData.ModelState.IsValid) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.ValidationSummary()
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (Model.ProcessingStatus)) {
    <div class="row">
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (!Model.ProcessingStatus)) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}

if (Model.FormMode == FormModeOption.DELETE) {

    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <p>
                Are you sure you want to remove Performance Year - @string.Format("({0})", Model.PerformanceYearName)?
            </p>
        </div>
    </div>
    }

    <div class="row">
        <div class="col-md-7">

            @if (Model.FormMode != FormModeOption.DELETE) {
                <div class="row">
                    @Html.Label("Performance Year Name", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.EditorFor(model => model.PerformanceYearName, new { htmlAttributes = new { @class = "form-control", @required = true } })
                    @Html.ValidationMessageFor(model => model.PerformanceYearName, "", new { @class = "text-danger" })
                </div>
                <div class="row">
                    @Html.Label("Start Date", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="row">
                    <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div> 
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })             
                </div>
                <div class="row">
                    @Html.Label("End Date", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="row">
                    <div class="input-group date" data-provide="datepicker" data-date-format="dd/mm/yyyy">
                         @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            }
            else {
                <div class="row">
                    @Html.Label("Perfromance Year Name", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.EditorFor(model => model.PerformanceYearName, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                </div>
                <div class="row">
                    @Html.Label("Start Date", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                </div>
                <div class="row">
                    @Html.Label("End Date", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @readOnly = true } })
                </div>
            }
            
            <br />
            <div class="row">
                <a href="@Url.Action("PerformanceYear", "Administration")" class="btn btn-md btn-primary" role="button">
                    <span class="glyphicon glyphicon-chevron-left glyphicon-chevron-left">
                    </span>&nbsp;Back To Performance Year Listing
                </a>
                @switch (Model.FormMode) {
                    case FormModeOption.CREATE: {
                            <button id="SubmitPerformanceYear" type="submit" class="btn btn-md btn-primary">
                                <span class="glyphicon glyphicon-plus">
                                </span>&nbsp;Create Performance Year
                            </button>
                            break;
                        }
                    case FormModeOption.EDIT: {
                            <button id="SubmitPerformanceYear" type="submit" class="btn btn-md btn-primary">
                                <span class="glyphicon glyphicon-pencil">
                                </span>&nbsp;Update Performance Year Details
                            </button>
                            break;
                        }
                    case FormModeOption.DELETE: {
                            <button id="SubmitPerformanceYear" type="submit" class="btn btn-md btn-danger">
                                <span class="glyphicon glyphicon-remove">
                                </span>&nbsp;Remove Performance Year
                            </button>
                            break;
                        }
                    default: {
                            break;
                        }
                }
            </div>
            <br />
        </div>
    </div>
}

@section Styles {
<link href="~/Scripts/datepicker3.css" rel="stylesheet" />

    <style>
        a:hover, a:visited, a:link, a:active {
            text-decoration: none;
        }

        .controls {
            margin-bottom: 10px;
        }

        .collapse-group {
            padding: 10px;
            border: 1px solid darkgrey;
            margin-bottom: 10px;
        }

        input[type="number"]::-webkit-outer-spin-button,
        input[type="number"]::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type="number"] {
            -moz-appearance: textfield;
        }
    </style>
}




@section Scripts {
<script src="~/Scripts/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy'
        });
    });
 </script>
}

SchoolProject.WebApplication/Views/Administration/PerformanceReviewPeriodLinking.cshtml
@model IEnumerable<SchoolProject.WebApplication.DTO.LinkPerformanceYearReviewPeriod>
@using SchoolProject.WebApplication.ViewModels;
@{
    ViewBag.Title = "PerformanceReviewPeriodLinking";
}

<h2>Performance Year Review Period Linking</h2>
<hr />
<div class="table-responsive">
    <table id="datatable" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    @Html.Raw("Performance Year")
                </th>
                <th>
                    @Html.Raw("Performance Year")
                </th>
                <th>
                    @Html.Raw("Review Period")
                </th>
                <th>
                    @Html.Raw("Status")
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PerformanceYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PerformanceYearStartEndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReviewPeriod)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StatusDescription)
                    </td>
                    <td>
                        <a href="@Url.Action("ManagePerformanceYearReviewPeriodLink", "Administration", new { pmReviewPeriodId = item.PMReviewPeriodId , formMode = FormModeOption.EDIT  })" class="btn btn-sm btn-primary" role="button">
                            <span class="glyphicon glyphicon-pencil">
                            </span>
                        </a>
                        <a href="@Url.Action("ManagePerformanceYearReviewPeriodLink", "Administration", new { pmReviewPeriodId = item.PMReviewPeriodId, formMode = FormModeOption.DELETE  })" class="btn btn-sm btn-danger" role="button">
                            <span class="glyphicon glyphicon-remove">
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-8">
        <a href="@Url.Action("CreatePerformanceYearReviewPeriodLink", "Administration")" class="btn btn-md btn-primary" role="button">
            <span class="glyphicon glyphicon-plus">
            </span>Link New Performance Year Review Period
        </a>
    </div>
</div>

SchoolProject.WebApplication/Views/Administration/PerformanceYear.cshtml
@model IEnumerable<SchoolProject.WebApplication.Models.AdminPerformanceYear>
@using SchoolProject.WebApplication.ViewModels;
@{
    ViewBag.Title = "PerformanceYear";
}

<h2>Performance Review Years</h2>
<hr />

<div class="table-responsive">
    <table id="datatable" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    @Html.Raw("Performance Year Description")
                </th>
                <th>
                    @Html.Raw("Start Date")
                </th>
                <th>
                    @Html.Raw("End Date")
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.Raw(item.PerformanceYearName)
                    </td>
                    <td>
                        @Html.Raw(item.StartDate.ToString("MMMM dd yyyy"))
                    </td>
                    <td>
                        @Html.Raw(item.EndDate.ToString("MMMM dd yyyy"))
                    </td>
                    <td>
                        <a href="@Url.Action("ManagePerformanceYear", "Administration", new { performanceYearId = item.PerformanceYearId , formMode = FormModeOption.EDIT  })" class="btn btn-sm btn-primary" role="button">
                            <span class="glyphicon glyphicon-pencil">
                            </span>
                        </a>
                        <a href="@Url.Action("ManagePerformanceYear", "Administration", new { performanceYearId = item.PerformanceYearId, formMode = FormModeOption.DELETE  })" class="btn btn-sm btn-danger" role="button">
                            <span class="glyphicon glyphicon-remove">
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        
    </table>
</div>
<div class="row">
    <div class="col-md-3 col-md-offset-9">
        <a href="@Url.Action("CreatePerformaceYear", "Administration")" class="btn btn-md btn-primary" role="button">
            <span class="glyphicon glyphicon-plus">
            </span>Add New Performance Year
        </a>
    </div>
</div>