SchoolProject.WebApplication/Controllers/PerformanceManagementController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolProject.WebApplication.DTO;
using SchoolProject.WebApplication.Models;
using SchoolProject.WebApplication.ServiceManager.Interface;
using SchoolProject.WebApplication.ViewModels;

namespace SchoolProject.WebApplication.Controllers {
    [Authorize]
    [HandleError]
    public class PerformanceManagementController : _BaseController {
        private readonly IAdmininstrationManager _iAdminstrationManager;
        private ApplicationDatabaseContext _dbContext;

        public PerformanceManagementController(IAdmininstrationManager iAdmininstrationManager) {
            _iAdminstrationManager = iAdmininstrationManager;
            _dbContext = new ApplicationDatabaseContext();
        }

        [HttpGet]
        public ActionResult ChangeUserPassword(string username) {
            if (string.IsNullOrEmpty(username))
                return RedirectToAction("Login", "Account");
            var user = _dbContext.Users.FirstOrDefault(x => string.Compare(x.UserName, username, true) == 0);
            if (user != null) {
                return RedirectToAction("ChangePassword", "Account", new { userId = user.Id });
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult ManageReview(string username) {
            if (!string.IsNullOrEmpty(username)) {
                var modelView = new ManageReviewModelView();
                modelView.EmployeeReviewPeriods = GetEmployeeReviewPeriods(username);
                modelView.UserRole = GetUserRole(username);
                modelView.DirectReportReviews = GetDirectReportingReviewPeriods(username);
                return View(modelView);
            }
            return RedirectToAction("Login", "Account");
        }

        public string GetUserRole(string username) {
            var user = _dbContext.Users.Include(x => x.Roles).FirstOrDefault(x => string.Compare(x.UserName, username) == 0);

            if (user != null)
                if (user.Roles.Count > 0) {
                    var roleId = user.Roles.FirstOrDefault().RoleId;
                    return _dbContext.Roles.FirstOrDefault(x => string.Compare(x.Id, roleId, true) == 0).Name;
                }
            return ("Employee");
        }

        [HttpGet]
        public ActionResult CreateReviewDocument() {
            var userName = User.Identity.Name;
            var employee = GetEmployee(userName);
            if (employee != null) {
                var createReviewPeriodModel = new PerformanceReviewModelView() {
                    ReportingStructureId = employee.ReviewReportingStructureId,
                    ReviewPeriods = ReviewPeriods()
                };
                return View(createReviewPeriodModel);
            }
            else {
                var createReviewPeriodModel = new PerformanceReviewModelView() {
                    ProcessingStatus = false,
                    ProcessingStatusMessage = "Your Line Manager is not yet added, please ask System Administrator to add your Line Manager.",
                    ReviewPeriods = ReviewPeriods(),
                    ReportingStructureId = -1
                };
                return View(createReviewPeriodModel);
            }
        }

        [HttpPost]
        public ActionResult CreateReviewDocument(PerformanceReviewModelView createReviewPeriodModel) {
            if (ModelState.IsValid) {
                if (!PerformanceReviewPeriodExist(createReviewPeriodModel)) {
                    var pmReviewPeriod = TransformPMReview(createReviewPeriodModel);
                    _dbContext.PMReview.Add(pmReviewPeriod);
                    _dbContext.SaveChanges();
                    //Set PMReviewProgressStatus Content Creation
                    var setProgressStatus = CreatePMReviewProgressStatus(1, pmReviewPeriod.PMReviewId);

                    var reviewName = createReviewPeriodModel.ReviewPeriods.FirstOrDefault(x => string.Compare(x.ValueText,
                                                  createReviewPeriodModel.ReviewPeriodId.ToString()) == 0).DisplayText;
                    createReviewPeriodModel.ReviewPeriodId = 0;
                    createReviewPeriodModel.ProcessingStatus = true;
                    createReviewPeriodModel.ProcessingStatusMessage = string.Format("Successfully created Performance Review Period {0}", reviewName);
                }
                else {
                    createReviewPeriodModel.ProcessingStatus = false;
                    createReviewPeriodModel.ProcessingStatusMessage = "Performance Review already exist, please complete review or create " +
                                                                  "a different Peformance Review Period.";
                }

            }

            return View(createReviewPeriodModel);
        }

        private bool PerformanceReviewPeriodExist(PerformanceReviewModelView createReviewPeriodModel) {
            var result = _dbContext.PMReview.FirstOrDefault(x => x.DateDeleted == null &&
                                                   x.PMReviewPeriodId == createReviewPeriodModel.ReviewPeriodId &&
                                                   x.ReviewReportingStructureId == createReviewPeriodModel.ReportingStructureId);
            return result == null ? false : true;

        }

        private bool CreatePMReviewProgressStatus(int processStageId, int pmReviewId) {
            var employee = GetEmployee(User.Identity.Name);
            var progressStage = new PMReviewProgressStatus() {
                ProcessStageId = processStageId,
                PMReviewId = pmReviewId,
                DateCreated = DateTime.Now,
                CreatedBy = string.Format("{0} {1}", employee.Owner.Name, employee.Owner.Surname),
                StatusId = 1,
                DateModified = DateTime.Now,
                ModifiedBy = string.Format("{0} {1}", employee.Owner.Name, employee.Owner.Surname),
                StartDate = DateTime.Now,
                EndDate = DateTime.Now
            };
            _dbContext.PMReviewProgressStatus.Add(progressStage);
            _dbContext.SaveChanges();
            return (true);
        }

        private PMReview TransformPMReview(PerformanceReviewModelView createReviewPeriodModel) {
            var employee = GetEmployee(User.Identity.Name);
            return (new PMReview() {
                ReviewReportingStructureId = createReviewPeriodModel.ReportingStructureId,
                PMReviewPeriodId = createReviewPeriodModel.ReviewPeriodId,
                DateCreated = DateTime.Now,
                CreatedBy = string.Format("{0} {1}", employee.Owner.Name, employee.Owner.Surname),
                StatusId = 1,
                DateModified = DateTime.Now,
                ModifiedBy = string.Format("{0} {1}", employee.Owner.Name, employee.Owner.Surname)
            });
        }

        public PMReviewReportingStructure GetEmployee(string userName) {
            var employee = _dbContext.PMReviewReportingStructure.Include(x => x.Owner).
                           FirstOrDefault(x => string.Compare(x.Owner.NetworkUsername, userName, true) == 0 && x.DateDeleted == null);
            return (employee);
        }

        public List<SelectionOptions> ReviewPeriods() {
            var results = new List<SelectionOptions>();
            var reviewPeriods = _dbContext.PMReviewPeriod.Where(x => x.DateDeleted == null).Include(x => x.ReviewPeriod).Include(x => x.PerformanceYear).ToList();
            foreach (var review in reviewPeriods) {
                results.Add(new SelectionOptions() {
                    ValueText = review.PMReviewPeriodId.ToString(),
                    DisplayText = string.Format("{0} - {1}", review.PerformanceYear.PerformanceYearName, review.ReviewPeriod.ReviewPeriodName)
                });
            }
            return (results);
        }

        public List<ManagePerformanceReview> GetEmployeeReviewPeriods(string usernmame) {
            var performanceReviews = new List<ManagePerformanceReview>();

            var filterReviews = _dbContext.PMReview.Where(x => x.DateDeleted == null && x.ReportingStructure.Owner.NetworkUsername == usernmame).
                              Include(x => x.ReportingStructure).Include(x => x.PMReviewPeriod).
                              Include(x => x.PMReviewPeriod.PerformanceYear).Include(x => x.PMReviewPeriod.ReviewPeriod).
                              Include(x => x.ReportingStructure.Manager).Include(x => x.ReportingStructure.Owner).
                              Include(x => x.ReportingStructure.DocumentType).Include(x => x.PMReviewPeriod.PerformanceYear).
                              Include(x => x.PMReviewPeriod.ReviewPeriod);
            var reviewIds = filterReviews.Select(x => x.PMReviewId).ToList();
            var reviewStages = _dbContext.PMReviewProgressStatus.Where(x => reviewIds.Contains(x.PMReviewId)).Include(x => x.ProcessStage).ToList();
            foreach (var review in filterReviews) {
                var stage = reviewStages.OrderByDescending(x => x.ProcessStageId).FirstOrDefault(x => x.PMReviewId == review.PMReviewId);
                performanceReviews.Add(new ManagePerformanceReview() {
                    PerformancereviewPeriodStageId = stage.PMReviewProgressStatusId,
                    ProcessStageId = stage.ProcessStageId,
                    ReviewStageName = stage.ProcessStage.ProcessStageName,
                    PMReviewId = stage.PMReviewId,
                    ReviewPeriodName = string.Format("{0} - {1}", review.PMReviewPeriod.PerformanceYear.PerformanceYearName,
                                                                  review.PMReviewPeriod.ReviewPeriod.ReviewPeriodName),

SchoolProject.WebApplication/Views/PerformanceManagement/CreateReviewDocument.cshtml
@model SchoolProject.WebApplication.ViewModels.PerformanceReviewModelView
@using SchoolProject.WebApplication.ViewModels;

@{
    ViewBag.Title = "Create Performance Review";
}
<h2>Create New Performance Review</h2>
<hr />

@using (Html.BeginForm("CreateReviewDocument", "PerformanceManagement", FormMethod.Post, new { @id = "CreatePerformanceReviewForm" })) {
 @Html.HiddenFor(model => model.ReportingStructureId)
    for (int i = 0; i < Model.ReviewPeriods.Count; i++) {
        @Html.HiddenFor(model => Model.ReviewPeriods[i].ValueText)
        @Html.HiddenFor(model => Model.ReviewPeriods[i].DisplayText)
    }
 @*Display Error messages*@
if (!ViewData.ModelState.IsValid) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.ValidationSummary()
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (Model.ProcessingStatus)) {
    
    <div class="row">
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (!Model.ProcessingStatus)) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.Raw(Model.ProcessingStatusMessage)
            </p>
        </div>
    </div>
}
    <div class="row">
        <div class="col-md-6">

               <div class="row">
                    @Html.Label("Select Performance Review", htmlAttributes: new { @class = "control-label" })<br />
                    @Html.DropDownList("ReviewPeriodId", new SelectList(Model.ReviewPeriods, "ValueText", "DisplayText"), string.Format("- Please Select {0} -", "Review Period"), new { @class = "form-control", @required = true })
                    @Html.ValidationMessageFor(model => model.ReviewPeriodId, "", new { @class = "text-danger" })
                </div>           
            <br />
            <div class="row">
                    <a href="@Url.Action("ManageReview", "PerformanceManagement", new {username = User.Identity.Name})" class="btn btn-md btn-primary" role="button">
                        <span class="glyphicon glyphicon-chevron-left glyphicon-chevron-left">
                        </span>&nbsp;Back To Performance Reviews Listing
                    </a>
                @if (Model.ReportingStructureId > 0){
                    <button id="SubmitCreateReview" type="submit" class="btn btn-md btn-primary">
                        <span class="glyphicon glyphicon-plus">
                        </span>&nbsp;Add New Performance Review
                    </button>
                }
            </div>
            <br />
        </div>

    </div>

}

SchoolProject.WebApplication/Views/PerformanceManagement/ManageReview.cshtml
@model SchoolProject.WebApplication.ViewModels.ManageReviewModelView
@using SchoolProject.WebApplication.ViewModels
@{
    ViewBag.Title = "ManageReview";
}

<h2>Manage Review</h2>
<hr />
@if (Model.EmployeeReviewPeriods != null) {
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>@Html.Raw("Employee")</th>
                    <th>@Html.Raw("Line Manager")</th>
                    <th>@Html.Raw("Document Type")</th>
                    <th>@Html.Raw("Own Document")</th>
                    <th>@Html.Raw("Performance Review Name")</th>
                    <th>@Html.Raw("Review Stage")</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.EmployeeReviewPeriods) {
                    <tr>
                        <td>@Html.Raw(item.EmployeeName)</td>
                        <td>@Html.Raw(item.LineManagerName)</td>
                        <td>@Html.Raw(item.DocumentType)</td>
                        <td>@Html.Raw("Yes")</td>
                        <td>@Html.Raw(item.ReviewPeriodName)</td>
                        <td>@Html.Raw(item.ReviewStageName)</td>
                        <td>
                            @if (item.ReviewStageName == ReviewProcessStatus.Content_Creation.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("AddPerformanceReviewContents", "PerformanceManagement", new { performanceReviewId = item.PMReviewId,
                                        formProcessingMode = FormModeOption.CREATE
                                     })">
                                    <span class="glyphicon glyphicon-plus">
                                    </span>&nbsp;Add Review Contents
                                </a>
                            }
                            @if (item.ReviewStageName == ReviewProcessStatus.Content_Creation_Completed.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("ScoreReview", "PerformanceManagement",
                                                                                     new { performanceReviewId = item.PMReviewId })">
                                    <span class="glyphicon glyphicon-pencil">
                                    </span>&nbsp;Score Review
                                </a>
                            }
                            @if (item.ReviewStageName == ReviewProcessStatus.Scoring_Completed.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("ViewReviewResult", "PerformanceManagement",
                                                                                     new { performanceReviewId = item.PMReviewId })">
                                    <span class="glyphicon glyphicon-stats">
                                    </span>&nbsp;View Review Results
                                </a>
                            }
                        </td>
                    </tr>
                }

                @foreach (var item in Model.DirectReportReviews) {
                    <tr>
                        <td>@Html.Raw(item.EmployeeName)</td>
                        <td>@Html.Raw(item.LineManagerName)</td>
                        <td>@Html.Raw(item.DocumentType)</td>
                        <td>@Html.Raw("No")</td>
                        <td>@Html.Raw(item.ReviewPeriodName)</td>
                        <td>@Html.Raw(item.ReviewStageName)</td>
                        <td>
                            @if (item.ReviewStageName == ReviewProcessStatus.Content_Creation.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("AddPerformanceReviewContents", "PerformanceManagement", new { performanceReviewId = item.PMReviewId,
                                        formProcessingMode = FormModeOption.CREATE
                                     })">
                                    <span class="glyphicon glyphicon-plus">
                                    </span>&nbsp;Add Review Contents
                                </a>
                            }
                            @if (item.ReviewStageName == ReviewProcessStatus.Content_Creation_Completed.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("ScoreReview", "PerformanceManagement",
                                                                                     new { performanceReviewId = item.PMReviewId })">
                                    <span class="glyphicon glyphicon-pencil">
                                    </span>&nbsp;Score Review
                                </a>
                            }
                            @if (item.ReviewStageName == ReviewProcessStatus.Scoring_Completed.ToString().Replace("_", " ")) {
                                <a role="button" class="btn btn-sm btn-primary" href="@Url.Action("ViewReviewResult", "PerformanceManagement",
                                                                                     new { performanceReviewId = item.PMReviewId })">
                                    <span class="glyphicon glyphicon-stats">
                                    </span>&nbsp;View Review Results
                                </a>
                            }
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
}

SchoolProject.WebApplication/Views/PerformanceManagement/ScoreReview.cshtml
@model SchoolProject.WebApplication.ViewModels.ScoreReviewViewModel
@using SchoolProject.WebApplication.ViewModels
@{
    ViewBag.Title = "Performance Review Scoring";
}
<h2>Manage Performance Review Contents</h2>
<hr />
@*Display Error messages*@
@if (!ViewData.ModelState.IsValid) {
    <div class="row">
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <p>
                @Html.ValidationSummary()
            </p>
        </div>
    </div>
}

    @*Display Processing Status*@
    @if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (!Model.ProcessingStatus)) {
        <div class="row">
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <p>
                    @Html.Raw(Model.ProcessingStatusMessage)
                </p>
            </div>
        </div>
    }

    @*Display Processing Status*@
    @if ((!string.IsNullOrEmpty(Model.ProcessingStatusMessage)) && (Model.ProcessingStatus)) {
        <div class="row">
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <p>
                    @Html.Raw(Model.ProcessingStatusMessage)
                </p>
            </div>
        </div>
    }

    @if ((Model.CurrentReviewStatus == ReviewProcessStatus.Content_Creation_Completed)) {
        using (Html.BeginForm("ScoreReview", "PerformanceManagement", FormMethod.Post, new { @id = "ManageScoreReview" })) {

            <div class="panel panel-success" style="border-color:#1c84c6">
                <a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="trigger collapsed">
                    <div class="panel-heading" role="tab" id="headingOne" style="background-color:#1c84c6">
                        <h4 class="panel-title">
                            <span style="color:#ffffff">Performance Review Score Update</span>
                        </h4>
                    </div>
                </a>
                <div id="collapseOne" class="panel-collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body" style="margin-right:12px;margin-left:12px">

                        @if (Model.MeasureId > 0) {
                            @Html.HiddenFor(model => model.MeasureId)
                            @Html.HiddenFor(model => model.PerformanceReviewId)
                            @Html.HiddenFor(model => model.IsLineManager)
                            @Html.HiddenFor(model => model.CurrentReviewStatus)
                            @Html.HiddenFor(model => model.MeasureName)
                            @Html.HiddenFor(model => model.MeasureWeight)
                            @Html.HiddenFor(model => model.MaximumScore)
                            @Html.HiddenFor(model => model.Username)
                            @Html.HiddenFor(model => model.ManagerUsername)
                            @Html.HiddenFor(model => model.StrategicGoal)
                            @Html.HiddenFor(model => model.Objective)
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="row">
                                        @Html.Label("Strategic Goal", htmlAttributes: new { @class = "control-label" })<br />
                                        @Html.Raw(Model.StrategicGoal)
                                    </div>
                                    <div class="row">
                                        @Html.Label("Objective", htmlAttributes: new { @class = "control-label" })<br />
                                        @Html.Raw(Model.Objective)
                                    </div>
                                    <div class="row">
                                        @Html.Label("Measure", htmlAttributes: new { @class = "control-label" })<br />
                                        @Html.Raw(string.Format("{0} - <b>(Weight {1}%)</b>", Model.MeasureName, decimal.Round(Model.MeasureWeight, 2, MidpointRounding.AwayFromZero)))
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="row">
                                        @Html.Label("Score", htmlAttributes: new { @class = "control-label" })<br />
                                        @Html.TextBoxFor(model => model.Score, new { @class = "form-control", @required = true })
                                    </div>
                                    <div class="row">
                                        @Html.Label("Comments", htmlAttributes: new { @class = "control-label" })<br />
                                        @Html.TextAreaFor(model => model.CaptureComments, new { @class = "form-control" })
                                    </div>
                                    <div class="col-md-offset-8 col-md-4">
                                        <br />
                                        <button type="submit" class="btn btn-sm btn-primary" role="button">
                                            <span class="glyphicon glyphicon-plus-sign">
                                            </span>&nbsp;Update Measure Score
                                        </button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

            if (Model.ReviewContents.Count > 0) {
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>@Html.Raw("Strategic Goal")</th>
                            <th>@Html.Raw("Objective")</th>
                            <th>@Html.Raw("Measure")</th>
                            <th>@Html.Raw("Weight")</th>
                            <th>@Html.Raw("Employee Score")</th>
                            <th>@Html.Raw("Manager Score")</th>
                            <th>@Html.Raw("Comments - Employee")</th>
                            <th>@Html.Raw("Comments - Manger")</th>
                            <th></th>
                        </tr>
                        @foreach (var group in Model.ReviewContents.GroupBy(x => x.StrategicGoalName)) {
                            <tr class="group-header">
                                <td colspan="9" style="text-align:center;font-weight:bold; cursor:pointer">
                                    @Html.Raw(string.Format("{0} - Total Weight {1} %", @group.Key, decimal.Round(@group.Sum(x => x.MeasureWeight), 2, MidpointRounding.AwayFromZero)))
                                </td>
                            </tr>
                            foreach (var item in group) {
                                <tr>
                                    <td>@Html.Raw(item.StrategicGoalName)</td>
                                    <td>@Html.Raw(item.ObjectiveName)</td>
                                    <td>@Html.Raw(item.MeasureName)</td>
                                    <td>@Html.Raw(item.MeasureWeight)</td>
                                    <td>@Html.Raw(item.EmployeeScore)</td>
                                    <td>@Html.Raw(item.ManagerScore)</td>
                                    <td>@Html.Raw(item.EmployeeComments)</td>
                                    <td>@Html.Raw(item.ManagerComments)</td>
                                    <td>
                                        <a role="button"  class="btn btn-sm btn-primary" href="@Url.Action("ScoreReview", "PerformanceManagement",
                                                             new { performanceReviewId = Model.PerformanceReviewId, measureId = item.MeasureId })">
                                            <span class="glyphicon glyphicon-pencil" style="color:white; font-weight:400">
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>

                <div class="row">
                    <div class="col-md-offset-4 col-md-8">
                        <a href="@Url.Action("ManageReview", "PerformanceManagement", new { username = Model.Username})" class="btn btn-md btn-primary" role="button">
                            <span class="glyphicon glyphicon-chevron-left glyphicon-chevron-left">
                            </span>&nbsp;Back To Performance Reviews Listing
                        </a>
                        @if (string.Compare(User.Identity.Name, Model.ManagerUsername, true) == 0) {
                            <a href="@Url.Action("ConfirmReviewScoring", "PerformanceManagement",
                                new {performanceReviewId = Model.PerformanceReviewId, managerUsername = Model.ManagerUsername })" class="btn btn-md btn-primary" role="button">
                                <span class="glyphicon glyphicon-pencil">
                                </span>&nbsp;Comfirm Performance Review Contents
                            </a>
                        }
                    </div>
                </div>
            }

        }
    }
    else {
        <div class="row">
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <p>
                    @Html.Raw("Performance Review Scoring Is Completed. Navigate to Manage Reviews and view the review scores!!")
                </p>
            </div>
        </div>
    }

    @section Styles {
        <style>
            a:hover, a:visited, a:link, a:active {
                text-decoration: none;
            }

            .controls {
                margin-bottom: 10px;
            }

            .collapse-group {
                padding: 10px;
                border: 1px solid darkgrey;
                margin-bottom: 10px;
            }


            input[type="number"]::-webkit-outer-spin-button,
            input[type="number"]::-webkit-inner-spin-button {
                -webkit-appearance: none;
                margin: 0;
            }

            input[type="number"] {
                -moz-appearance: textfield;
            }
        </style>
    }

    @section Scripts {
        <script type="text/javascript">
            $(document).ready(function () {

                //initial bootstrap tooltip and hide after click event
                $('body').tooltip({
                    selector: '[data-toggle="tooltip"], [title]:not([data-toggle="popover"])',
                    trigger: 'hover',
                    container: 'body'
                }).on('click mousedown mouseup', '[data-toggle="tooltip"], [title]:not([data-toggle="popover"])', function () {
                    $('[data-toggle="tooltip"], [title]:not([data-toggle="popover"])').tooltip('destroy');
                });

                $(function () {
                    $('.group-header').click(function () {
                        $(this).nextUntil('.group-header').toggle();
                    });
                });

            });
        </script>
    }